---
- name: Converge
  hosts: all

  vars:
    vagrant_update: true

  pre_tasks:
    - name: Update apt cache on Debian systems.
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Update pacman cache on Archlinux systems.
      community.general.pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == "Archlinux"

  tasks:
    - name: Include vagrant
      ansible.builtin.include_role:
        name: jeffreyjs.vagrant
